import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <ul>
            <li> <Link href="/home">Home</Link> </li>
            <li> <Link href="/about">About</Link> </li>
            <li> <Link href="/service">Service</Link> </li>
 
          </ul>
        </div>
        {children}
     <h1>Ami Footer</h1>
        </body>
    </html>
  )
}
